# Generated by Django 5.1.1 on 2024-12-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_order_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='design',
        ),
    ]
