# Generated by Django 5.1.1 on 2024-12-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_ordered']},
        ),
    ]
