# Generated by Django 5.1.1 on 2024-12-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArnoldTONY', '0004_alter_profile_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_design',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_designs/'),
        ),
    ]
