# Generated by Django 5.1.1 on 2024-12-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArnoldTONY', '0005_product_user_description_product_user_design'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user_design',
        ),
    ]
