# Generated by Django 5.1.1 on 2024-12-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArnoldTONY', '0006_remove_product_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='user_design_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_design/'),
        ),
    ]
